### ISSUE TITLE
Testnet

### ISSUE THREAD

**Issue by AdamSEY** [Har01d/CashAddressPHP#2]
Can you add support for testnet?

**Comment by AdamSEY** [comment]
its still not working try with this address:
mqsz3HLxxRdkiTbVKTmiGSRzNUysmDmN3K

**Comment by DesWurstes** [comment]
It returns `bchtest:qpc6kuesfg9r38cvyc74cdelsptk3hlxygxrd88nf0`, which is the same result with https://cashaddress.github.io/index.html#mqsz3HLxxRdkiTbVKTmiGSRzNUysmDmN3K

Can you please show your code? And make sure to use my repo's code (https://github.com/DesWurstes/CashAddressPHP) before the pull request gets merged.

**Comment by AdamSEY** [comment]
Now it's worked! Thanks for your fast response and good work!
