### ISSUE TITLE
wrong bitcoin cash address

### ISSUE THREAD

**Issue by bullcandle** [Har01d/CashAddressPHP#7]
Hi mate, I have tried to convert the legacy address "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa"

```
include('CashAddress.php');
echo $r = \CashAddress\CashAddress::old2new("1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa");
```

As result I got "qp3wjpa3tjlj042z2wv7hahsldgwhwy0rq**llgq6ut7** instead of "qp3wjpa3tjlj042z2wv7hahsldgwhwy0rq**9sywjpyy**"

Last 8 symbols are different

Conf: Apache/2.4.34 (Win32) OpenSSL/1.1.0i PHP/7.2.9  (Windows Xamp xampp-win32-7.2.9-0-VC15-installer.exe)

**Comment by DesWurstes** [comment]
It requires 64 bit PHP.

**Comment by bullcandle** [comment]
Thanks, I have transfer it to Linux with 64bit PHP and it's working correctly
